default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        name: Autoflake - Full repo
        exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|Gphl|LNLS|MAXIV|SOLEIL|ANSTO))
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-duplicate-keys
      - id: autoflake
        name: Autoflake - ANSTO
        files: mxcubecore/HardwareObjects/ANSTO
        args:
          - --expand-star-imports
          - --ignore-init-module-imports
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      name: Black - Full repo
      language_version: python3.9
      exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|Gphl|LNLS|MAXIV|SOLEIL))
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: (deprecated/|mxcubecore/HardwareObjects/(ALBA|ASLS|DESY|EMBL|ESRF|Gphl|LNLS|MAXIV|SOLEIL))
      - id: check-case-conflict
      - id: check-merge-conflict
        # exclude files where underlines are not distinguishable from merge conflicts
        exclude: /README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: requirements-txt-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Import Sort - ANSTO
        args:
          - --settings=.
        files: mxcubecore/HardwareObjects/ANSTO
        exclude: /__init__\.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      name: Flake8 - ANSTO
      additional_dependencies: ["flake8-bugbear==20.1.4"]
      files: mxcubecore/HardwareObjects/ANSTO
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
