language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
#matrix:
#  include:
#    - python: 3.7
#      dist: xenial
#      sudo: true
install:
  - travis_retry python -m pip install -r requirements.txt
script:
  - python -m pytest
#  - pylint -E HardwareObjects/EMBL
#  - pylint -E *py
#  - pylint -E HardwareObjects/*py
#  - pylint -E HardwareObjects/abstract/*py
#  - pylint -E HardwareObjects/mockup/*py

