[tool.poetry]
name = "mxcubecore"
version = "0.1.0"
description = "Core libraries for the MXCuBE application"
authors = ["The MXCuBE developers <mxcube@mxcube.org>"]
maintainers = ["ANSTO, Clayton Synchrotron"]
readme = "README.md"

[[tool.poetry.source]]
name = "cachedpypi"
url = "https://pypi.asci.synchrotron.org.au/root/pypi/+simple"
default = true

[[tool.poetry.source]]
name = "asci-dev"
url = "https://pypi.asci.synchrotron.org.au/asci/dev/+simple"
secondary = true

[[tool.poetry.source]]
name = "asci-prod"
url = "https://pypi.asci.synchrotron.org.au/asci/prod/+simple"
secondary = true

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
gevent = "21.12.0"
greenlet = "1.1.2"
jsonpickle = "2.1.0"
jsonschema = "4.4.0"
lxml = "4.7.1"
matplotlib = "3.5.1"
ophyd = "1.6.3"
numpy = "1.21.4"
pillow = "9.0.1"
pre-commit = "2.17.0"
pydantic = "1.9.0"
pydispatcher = "2.0.5"
pyepics = "3.5.1"
pylint = "2.12.2"
pytest = "7.0.1"
suds-py3 = "1.4.5.0"
"ruamel.yaml" = "0.17.21"
scipy = "1.7.3"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
