# The class to initialise, and init parameters
_initialise_class:
    class: mxcubecore.HardwareObjects.Beamline.Beamline
    # Further key-value pairs here will be passed to the class init
#    mode: devel

# objects
#
# Eventually all objects should use the yaml config system like Beamline,
# but for now we can leave them as xml
#
# NBNB some objects that do not currently have their own config files
# would need those added (e.g. the centring methods)
#
_objects:
    # The !!o0map and the lines starting with '- ' give you an *orderd* dictionary
    # And thus a reproducible loading order
    !!omap
    # The values are the file paths to the configuration file for the
    # object, relative to the configuration file path(s)
    #
    # NB - the order is *NOT* arbitrary, as signal connnections are set
    # on one object that require the other to be already loaded.
    #
    # Hardware:
    - session: session.xml
    - machine_info: machine_info.xml
    - detector: detector.xml
    - beam: beam_info.xml
    - energy: energy.xml
    - transmission: transmission.xml
    - flux: flux.xml
    - resolution: resolution.xml
    - safety_shutter: safety_shutter.xml
    - fast_shutter: fast_shutter.xml
    - hutch_interlock: hutch_trigger.xml
    - sample_changer: sc.xml
    - sample_changer_maintenance: sc_maint.xml
    - diffractometer: diffractometer.xml
    - lims: lims.xml
    - sample_view: sample_view.xml
    - queue_manager: queue.xml
    - queue_model: queue_model.xml

    # Procedures:
    - xml_rpc_server: xml_rpc_server.xml
    - workflow: edna_params.xml
    - collect: collect.xml
    - xrf_spectrum: xrf.xml
    - energy_scan: energy_scan.xml
#    - gphl_workflow: gphl-workflow.xml
#    - gphl_connection: gphl-setup.xml
#    - centring: centring.xml
    # Analysis:
    - offline_processing: offline_processing.xml
    - online_processing: online_processing.xml
    - characterisation: characterisation.xml
    # - data_publisher: data_publisher.xml

    # - beam_realign: # Skipped - optional

# Non-object attributes:
advanced_methods:
  - MeshScan
  - XrayCentering

tunable_wavelength: true
disable_num_passes: true
run_online_processing: true
run_number: 1
click_centring_num_clicks: 3

default_acquisition_parameters:
    default:
        # Default values, also used for standard acquisition.
        # Values not given in other dictionaries are taken from here
        exp_time: 0.02        # exposure time
        osc_start: 0.0  # Only used if no current angle can be found
        osc_range: 0.1
        num_passes: 1
        first_image: 1
        overlap: 0
        num_images: 1
        detector_mode: 1 # Remove as not in practice used ?
        inverse_beam: false
        take_dark_current: true
        skip_existing_images: true
        take_snapshots: true
        # NB 'compression' not added as apparently never used

    helical:
        # Defaults for helical scan. Missing values are taken from default
        number_of_images: 100

    characterisation:
        # Defaults for chareacterisation. Missing values are taken from default
        exp_time: 0.05       # exposure time
        osc_range: 1
        overlap: -89
        num_images: 4

    mesh:
        # Defaults for 'advanced' acquisition. Missing values are taken from default
        exp_time: 10       # exposure time
        range: 10
        num_images: 100
        cell_counting: zig-zag
        cell_spacing: vertical, horizontal
        mesh_center: top-left

    default_ansto:
        # The commented parameteres refer to the `plan` parameters
        # defined in Daniel's experiment.yml file.
        # We follow mxcube naming convention for now
        # See the SUPPORTED_ACQ_PARAMETERS in the Bseamline class
        # to see the supported acquisition parameters. Additional parameters
        # can be added depending on the workflow

        # MXCUBE SUPPORTED_ACQ_PARAMETERS
        exp_time: 18.0 # exposure_time
        osc_range: 0.1 # delta
        num_passes: 1 # NOT defined in the experiment.yml file ???
        run_number: 1 # NOT defined in the experiment.yml file ???
        overlap: 0 # NOT defined in the experiment.yml file ???
        num_images: 1800 # no_frames
        inverse_beam: false # NOT defined in the experiment.yml file ???
        take_dark_current: true # NOT defined in the experiment.yml file ???
        skip_existing_images: true # NOT defined in the experiment.yml file ???
        take_snapshots: true # NOT defined in the experiment.yml file ???

        # Additional parameters
        additional_parameters:
            attenuation_setpoint: 90.0
            beamstop_setpoint: 48.998
            distance_setpoint: 260.957675331
            energy_setpoint: 12.999881743
            frequency: 100.0
            osc_rate: 10.0
            start_frame: 1
            wedge: 180.0

available_methods:
    datacollection: True
    characterisation: True
    helical: True
    xrf_scan: True
    energy_scan: True
    mesh_scan: False
