name: Test Coverage
on:
  push:
jobs:
  pytest-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run and write pytest
      run: |
        set -o pipefail
        poetry run pytest --cov=src/name --cov-report term-missing | tee pytest-coverage.txt

    - name: Pytest coverage comment
      id: coverage-comment
      uses: MishaKav/pytest-coverage-comment@v1.1.35
      with:
        pytest-coverage-path: ./pytest-coverage.txt

    - name: Check the output coverage
      if: ${{ github.event_name == 'push' }}
      run: |
        echo "Coverage Report - ${{ steps.coverage-comment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverage-comment.outputs.color }}"
